class SpanishLanguageStrategy {
    constructor() {
        this.translations = {
            searchPlaceholder: "Buscar uniformes, camisetas, tacos...",
            immediateDelivery: "🛒 ENTREGA INMEDIATA",
            colorBlindMode: "🎨 MODO DALTÓNICO",
            normalView: "Visualización normal",
            stopAudio: "⏹️ DETENER AUDIO",
            audioMode: "🔊 MODO AUDITIVO",
            languageButton: "🇺🇸 ENGLISH",
            lightMode: "☀️ MODO CLARO",
            darkMode: "🌙 MODO OSCURO",
            topPlayers: "⭐ LOS 10 MEJORES DEL MUNDO",
            popular: "🔥 POPULARES",
            professionalSpeed: "Velocidad Profesional",
            totalControl: "Control Total",
            professionalFutsal: "Futsala Profesional",
            storeDescription: "La tienda especializada en fútbol más completa para jugadores, aficionados y clubes deportivos.",
            safePurchase: "🛡️ Compra segura",
            personalizedService: "📞 Atención personalizada",
            originalProducts: "⚽ Productos originales",
            worldCup2026: "🏆 Mundial 2026",
            socialNetworks: "Redes Sociales",
            countryShipping: "🚚 Envíos a todo el país",
            safePayments: "💳 Pagos seguros",
            easyReturns: "🔄 Cambios fáciles",
            factoryWarranty: "🛡 Garantía de fábrica",
            buyWhatsapp: "Comprar por WhatsApp",
            whatsappMessage: "Hola, estoy interesado en",
            home: "🏠 Inicio",
            clubs: "🛡 Clubes",
            nationalTeams: "👕 Selecciones",
            specials: "⭐ Especiales",
            shoes: "👟 Zapatos",
            kids: "👦🏻 Para niños",
            soccerShoes: "⚽ Zapatos Fútbol",
            futsalShoes: "🏟 Tenis Fútbol Sala",
            nikeCleats: "👟 Tacos Nike",
            adidasCleats: "👟 Tacos Adidas",
            pumaCleats: "👟 Tacos Puma",
            newBalanceCleats: "👟 Tacos New Balance",
            mizunoCleats: "👟 Tacos Mizuno",
            sgCleats: "👟 Tacos Atornillados (SG)",
            agCleats: "👟 Tacos Césped Artificial (AG)",
            budgetCleats: "👟 Tacos Económicos",
            futsalNike: "👟 Futbol Sala - Nike",
            futsalAdidas: "👟 Futbol Sala - Adidas",
            futsalJoma: "👟 Futbol Sala - Joma",
            futsalMizuno: "👟 Futbol Sala - Mizuno",
            futsalPuma: "👟 Futbol Sala - Puma",
            futsalDiadora: "👟 Futbol Sala - Diadora",
            futsalNewBalance: "👟 Futbol Sala - New Balance",
            naturalGrassCleats: "Tacos Césped Natural",
            futsalTennis: "Tennis Futsala",
            soccerUniforms: "Uniformes de Fútbol",
            categoriesTitle: "Categorías",
            categoriesDescription: "Categorías disponibles.",
            contactTitle: "Contacto",
            contactDescription: "Contacta con nosotros mediante WhatsApp.",
            productsTitle: "Productos",
            productsDescription: "Catálogo completo de artículos.",
            heroTitle: "TODO PARA EL FÚTBOL",
            heroDescription: "Uniformes, balones, tacos y accesorios para jugadores y aficionados.",
            seeProducts: "Ver Productos",
            addToCart: "Agregar al carrito",
            cartTitle: "Carrito",
            cartItems: "artículos",
            emptyCart: "El carrito está vacío.",
            subtotal: "Subtotal",
            tax: "Impuesto 10%",
            total: "Total a pagar",
            sendWhatsappOrder: "Enviar pedido por WhatsApp",
            clearCart: "Vaciar carrito",
            whatsappOrderIntro: "Hola, quiero realizar este pedido en PORTUFUTBOL:",
            videoTitle: "Video destacado",
            videoSubtitle: "Inspiración futbolera para elegir tu próximo producto"
        };
    }

    translate(key) {
        return this.translations[key] || key;
    }
}

class EnglishLanguageStrategy {
    constructor() {
        this.translations = {
            searchPlaceholder: "Search uniforms, jerseys, cleats...",
            immediateDelivery: "🛒 IMMEDIATE DELIVERY",
            colorBlindMode: "🎨 COLOR BLIND MODE",
            normalView: "Normal view",
            stopAudio: "⏹️ STOP AUDIO",
            audioMode: "🔊 AUDIO MODE",
            languageButton: "🇪🇸 ESPAÑOL",
            lightMode: "☀️ LIGHT MODE",
            darkMode: "🌙 DARK MODE",
            topPlayers: "⭐ TOP 10 PLAYERS IN THE WORLD",
            popular: "🔥 POPULAR",
            professionalSpeed: "Professional Speed",
            totalControl: "Total Control",
            professionalFutsal: "Professional Futsal",
            storeDescription: "The most complete football specialty store for players, fans, and sports clubs.",
            safePurchase: "🛡️ Safe purchase",
            personalizedService: "📞 Personalized support",
            originalProducts: "⚽ Original products",
            worldCup2026: "🏆 World Cup 2026",
            socialNetworks: "Social Networks",
            countryShipping: "🚚 Shipping nationwide",
            safePayments: "💳 Secure payments",
            easyReturns: "🔄 Easy exchanges",
            factoryWarranty: "🛡 Factory warranty",
            buyWhatsapp: "Buy through WhatsApp",
            whatsappMessage: "Hello, I am interested in",
            home: "🏠 Home",
            clubs: "🛡 Clubs",
            nationalTeams: "👕 National Teams",
            specials: "⭐ Specials",
            shoes: "👟 Shoes",
            kids: "👦🏻 Kids",
            soccerShoes: "⚽ Football Cleats",
            futsalShoes: "🏟 Futsal Shoes",
            nikeCleats: "👟 Nike Cleats",
            adidasCleats: "👟 Adidas Cleats",
            pumaCleats: "👟 Puma Cleats",
            newBalanceCleats: "👟 New Balance Cleats",
            mizunoCleats: "👟 Mizuno Cleats",
            sgCleats: "👟 Soft Ground Cleats (SG)",
            agCleats: "👟 Artificial Grass Cleats (AG)",
            budgetCleats: "👟 Budget Cleats",
            futsalNike: "👟 Futsal - Nike",
            futsalAdidas: "👟 Futsal - Adidas",
            futsalJoma: "👟 Futsal - Joma",
            futsalMizuno: "👟 Futsal - Mizuno",
            futsalPuma: "👟 Futsal - Puma",
            futsalDiadora: "👟 Futsal - Diadora",
            futsalNewBalance: "👟 Futsal - New Balance",
            naturalGrassCleats: "Natural Grass Cleats",
            futsalTennis: "Futsal Shoes",
            soccerUniforms: "Football Uniforms",
            categoriesTitle: "Categories",
            categoriesDescription: "Available categories.",
            contactTitle: "Contact",
            contactDescription: "Contact us through WhatsApp.",
            productsTitle: "Products",
            productsDescription: "Complete product catalog.",
            heroTitle: "EVERYTHING FOR FOOTBALL",
            heroDescription: "Uniforms, balls, cleats, and accessories for players and fans.",
            seeProducts: "View Products",
            addToCart: "Add to cart",
            cartTitle: "Cart",
            cartItems: "items",
            emptyCart: "The cart is empty.",
            subtotal: "Subtotal",
            tax: "10% tax",
            total: "Total to pay",
            sendWhatsappOrder: "Send order through WhatsApp",
            clearCart: "Clear cart",
            whatsappOrderIntro: "Hello, I want to place this order at PORTUFUTBOL:",
            videoTitle: "Featured video",
            videoSubtitle: "Football inspiration to choose your next product"
        };
    }

    translate(key) {
        return this.translations[key] || key;
    }
}

export { SpanishLanguageStrategy, EnglishLanguageStrategy };
